### ISSUE TITLE
options file is overwritten when cedille is run

### ISSUE THREAD

**Issue by mpickering** [cedille/cedille#29] opened 2018-10-15 14:30 UTC
I tried to specify where the directory for `import-directories` so I modified the `import-directories` line to look like

```
import-directories = "/nix/store/pyip7r00v1h5796m3lg49i895bqy34dx-cedille-1.0.0-lib" .
```

When I then launch emacs and press `M-s` to load cedille, the `~/.cedille/options` file seems to be overwritten and the value I placed in `import-directories` is removed. 

How should I be setting `import-directories`? Should I not directly modify this file?

**Comment by cwjnkins** [comment] 2018-10-15 15:42
The quick-fix for this is to use a directory-local options file. I'm not entirely sure what your directory layout is but it looks like you have perhaps separated the Cedille source from the library? If so, then (assuming you are trying to visit the files in "/nix/store/pyip7r00v1h5796m3lg49i895bqy34dx-cedille-1.0.0-lib" then add a local ".cedille" directory here with your options file.

The long answer to this is we simply failed to anticipate someone checking Cedille files outside of their home directory. We look for the options file by climbing parent directories until we reach "/" (which, we assumed, meant we would encounter "~/" along the way). If we don't find an options file, then we create one in "~/.cedille" (which is why your version of the file is getting overwritten).

The long-term fix for this should be simple enough -- make sure to also check "~/.cedille" after the traversal of parent directories fails before generating this file.

**Comment by cwjnkins** [comment] 2018-10-15 16:14
@mpickering Please try compiling Cedille at the branch issue-29 (https://github.com/cedille/cedille/tree/issue-29). If this works for you then likely it will be pulled and merged into master later today. I've already replicated your issue and confirmed this fix works on my machine.

**Comment by cwjnkins** [comment] 2018-10-15 22:37
I've cherry-picked the commit to branch release-1.0 (and added some tweaks to get it to compile). This should cleanly apply to the release v1.0.0.

As for passing the options file as a command line argument -- I think this could be a good feature to add, I will go ahead and open an issue for this, too.

**Comment by mpickering** [comment] 2018-10-16 10:38
I tried this patch and it no longer overwrites the file.

It doesn't seem to honour or use the import-directories option still. 

I have

```
import-directories = "/nix/store/gpxpj0ia9561q3y3rpbv7d0r3z3nihwg-cedille-1.0.0-lib" .
```

```
> ls /nix/store/gpxpj0ia9561q3y3rpbv7d0r3z3nihwg-cedille-1.0.0-liband.ced    datatype_test.ced  int.ced        is.ced         nonnorm.ced  sigma.ced  vector.ced
bool.ced   depcast.ced        int-ops.ced    list.ced       or.ced       sum.ced    vector-thms.ced
cast.ced   everything.ced     int-thms2.ced  list-thms.ced  product.ced  top.ced    wSigma2.ced
clist.ced  false.ced          int-thms3.ced  nat.ced        README.md    true.ced   wSigma.ced
cnat.ced   hastp.ced          int-thms.ced   nat-thms.ced   recType.ced  unit.ced
```

But when I load cedille, the module `sigma` can't be found still.

```
module test.

import sigma.
```

**Closed** 2018-10-16 16:09 UTC
Labels: bug
